# Copyright 2020 Tata Elxsi canonical@tataelxsi.onmicrosoft.com
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
    port:
        type: int
        description: 'Port'
        default: 5000
    gin_mode:
        type: string
        description: 'gin implements a HTTP web framework and possible values  are debug and release'
        default: 'release'

