# Copyright 2020 Tata Elxsi canonical@tataelxsi.onmicrosoft.com
# See LICENSE file for licensing details.
---
options:
    gin_mode:
        type: string
        description: 'gin implements a HTTP web framework and
                      possible values are debug and release'
        default: 'release'
